
server:
  port: 8081
spring:
  datasource:
      url: jdbc:h2:mem:appDb
      username: sawaf
      password: sawaf
      driverClassName: org.h2.Driver

#    url: jdbc:mysql://localhost:3306/angular-spring-security?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: P@$$w0rd@2292

  jpa:
    database-platform : org.hibernate.dialect.H2Dialect
#    show-sql: true
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:

#        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ahmelsawaf@gmail.com
    password: mluvjeulmpjrbylf
    properties:
      mail:
        smtp:
          auth: true
          starttls: true




#debug: true